name: build .Net Core
run-name: build .Net Core

on:
  workflow_dispatch:


  jobs:
    build-net:
      steps:
        - name: checkout
          use: actions/checkout@v4

        - name: Set up .net
          use: actions/setup-dotnet@v4
          with:
            dotnet-version: '3.1'
        - name: Build project
          run: dotnet build --configuration Release

        - name: Create build artifact
          run: |
            mkdir -p build-artifacts
            cp -r bin/Release/* build-artifacts/
            tar -czf build-artifact.tar.gz -C build-artifacts .

        - name: Upload build artifact
          uses: actions/upload-artifact@v4
          with:
            name: build-artifact
            path: build-artifact.tar.gz
            retention-days: 7