name: build .Net Core
run-name: build .Net Core

on:
  workflow_dispatch:


jobs:
  build-net:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1'

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build project
        run: dotnet build AapiPeliculas/AapiPeliculas.csproj --configuration Release

      - name: List files
        run: ls -la

      - name: Create build artifact
        run: |
            mkdir -p build-artifacts
            cp -r bin/Release/* build-artifacts/
            tar -czf build-artifact.tar.gz -C build-artifacts .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifact.tar.gz
          retention-days: 7